name: fletgo_user_app
description: Applicación de FletGO para Usuarios
version: 4.0.8+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mailer: ^3.2.1
  flutter_email_sender: ^3.0.1
  url_launcher: ^5.7.8
  flutter_bloc: ^4.0.0
  intl: ^0.16.1
  flutter:
    sdk: flutter
  tel_input: ^0.2.2
  giffy_dialog: ^1.6.1
  google_maps_flutter: ^0.5.21
  geolocator: ^5.1.5
  flutter_google_places:
  google_maps_webservice:
  flutter_credit_card: ^0.1.3
  stripe_payment: ^1.0.7
#  stripe_payment: 1.1.4
  image_picker: ^0.6.7+4
  http: ^0.12.1+17
  progress_dialog: ^1.2.2
  firebase_core:
  firebase_analytics:
  cloud_firestore: ^0.13.4
  cloud_functions:
  firebase_auth:
  firebase_database:
  firebase_storage:
  flutter_auth_buttons:
  google_sign_in: ^4.1.4
  rxdart:
  google_map_polyline:
  #sign_in_with_apple: ^3.0.0
  apple_sign_in: ^0.1.0
  cupertino_icons: ^0.1.2
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf